#include<bits/stdc++.h>
using namespace std;

int main()
{
    int A, B;

    cout << "OK, ENTER TWO INTEGER(A,B) TO PERFORM RELATIONAL OPERATION ON THEM: ";
    cin  >> A >> B;
    cout << "------------------------------------------------------------------------\n" << endl;

    cout << "\nRELATIONAL OPEREATION IN C++ : "  << endl;
    cout << "-------------------------------\n"  << endl;

    cout << "YOU ENTERD A = " << A << " & B = "  << B << endl;
    cout << "-----------------------------\n  "  << endl;


    cout << "1) EQUAL TO     : ( A == B) : " << A << " == " << B << " = " << ( A == B) << endl;
    cout << "2) NOT EQUAL TO : ( A != B) : " << A << " != " << B << " = " << ( A != B) << endl;
    cout << "3) GREATER THAN : ( A >  B) : " << A << "  > " << B << " = " << ( A  > B) << endl;
    cout << "4) LESS THAN    : ( A <  B) : " << A << "  < " << B << " = " << ( A  < B) << endl << endl;
    cout << "5) GREATER THAN OR EQUAL TO : ( A >= B) : " << A << " >= " << B << " = " << ( A >= B) << endl;
    cout << "6) LESS THAN OR EQUAL TO    : ( A <= B) : " << A << " <= " << B << " = " << ( A <= B) << endl;




    cout << "\n\t\t   --------------------------------------------------------------" << endl;
    cout << "\t\t        THIS IS THE END OF RELATIONAL OPERARTION! THANK YOU."        << endl;
    cout << "\t\t   --------------------------------------------------------------"   << endl;

    return 0;
}

